### ISSUE TITLE
Not writing to BigQuery

### ISSUE THREAD

**Issue by jonoellis** [sahava/web-scraper-gcp#2]
Hi Simo, Thanks for this - it looks really usefully. I followed your steps on https://www.simoahava.com/google-cloud/cookie-audit-with-google-bigquery/ and unfortunately I'm seeing the same issue as Allessandro - the VM started and crawled but doesn't pass data to BigQuery and doesn't shut down. Logs as below:

```
startup-script: Crawled https://XXXXXXXX.com/
startup-script: (node:8557) UnhandledPromiseRejectionWarning: Error: Protocol error: Connection closed. Most likely the page has been closed.
startup-script:     at Crawler.close (/web-scraper-gcp/node_modules/headless-chrome-crawler/lib/crawler.js:80:22)
startup-script:     at Page.close (/web-scraper-gcp/node_modules/puppeteer/lib/Page.js:883:5)
startup-script:     at assert (/web-scraper-gcp/node_modules/puppeteer/lib/helper.js:251:11)
startup-script: (node:8557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag--unhandled-rejections=strict(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
startup-script:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
startup-script:     at HCCrawler._request (/web-scraper-gcp/node_modules/headless-chrome-crawler/lib/hccrawler.js:349:21)
startup-script:     at Crawler.<anonymous> (/web-scraper-gcp/node_modules/headless-chrome-crawler/lib/helper.js:177:23)
startup-script: (node:8557) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is this something that I can fix?

**Comment by jonoellis** [comment]
Schema hadn't been set in BigQuery - user error.
